name: API Documentation

on:
  push:
    branches:
      - 'develop'

jobs:

  build:
    name: Generate API Docs
    if: (github.repository == 'codeigniter4/CodeIgniter4')
    runs-on: ubuntu-latest

    steps:
      - name: Identify
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "${GITHUB_ACTOR}"

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.2'
          extensions: intl, json, mbstring, mysqlnd, xdebug, xml, sqlite3
          coverage: xdebug

      - name: Download GraphViz for phpDocumentor
        run: |
          sudo apt-get install -yq graphviz

      - name: Download phpDocumentor
        run: |
          curl -L https://github.com/phpDocumentor/phpDocumentor/releases/download/v2.9.1/phpDocumentor.phar -o ./admin/phpDocumentor.phar

      - name: Prepare source
        run: |
          rm -rf ./build/api*
          mkdir -p ./build/api/docs
          cd build/api
          git init
          git remote add origin https://github.com/codeigniter4/api.git
          git fetch
          git checkout master
          git reset --hard origin/master
          rm -r docs/*

      - name: Make the new API docs
        run: |
          chmod +x ./admin/phpDocumentor.phar
          ./admin/phpDocumentor.phar
          cp -R ./api/build/* ./build/api/docs

      - name: Deploy API
        run: |
          cd ./build/api
          git add .
          git commit -m "API bot sync for ${GITHUB_SHA}"
          git push -f origin master
